services:
  front:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - $HOME/github.com/loicbourgois/miniciv/front:/usr/share/nginx/html:ro
      # - $HOME/github.com/loicbourgois/miniciv/nginx.conf:/etc/nginx/conf.d/default.conf:ro